#!/bin/bash
# Pre-build script for Vercel: downloads WASM and library assets
# that are normally generated by `make public` from git repos.
set -euo pipefail

WASM_BUILD_URL="https://files.openscad.org/playground/OpenSCAD-2025.03.25.wasm24456-WebAssembly-web.zip"
# CDN where pre-built assets are hosted (same as default BASE_URL)
CDN="https://ochafik.com/openscad2"

# Download WASM if not present
if [ ! -f src/wasm/openscad.wasm ]; then
  echo "Downloading OpenSCAD WASM build..."
  mkdir -p libs/openscad-wasm
  curl -fSL "$WASM_BUILD_URL" -o libs/openscad-wasm.zip
  ( cd libs/openscad-wasm && unzip -o ../openscad-wasm.zip )
  rm -f src/wasm
  ln -sf "$(pwd)/libs/openscad-wasm" src/wasm
fi

# Download library zips from CDN if not present locally
echo "Downloading library zips from CDN..."
mkdir -p public/libraries
for lib in \
  fonts.zip openscad.zip NopSCADlib.zip BOSL.zip BOSL2.zip \
  boltsparts.zip OpenSCAD-Snippet.zip funcutils.zip FunctionalOpenSCAD.zip \
  YAPP_Box.zip MCAD.zip Stemfie_OpenSCAD.zip pathbuilder.zip \
  openscad_attachable_text3d.zip brailleSCAD.zip lasercut.zip \
  closepoints.zip plot-function.zip smooth-prim.zip UB.scad.zip \
  openscad-tray.zip; do
  if [ ! -f "public/libraries/$lib" ]; then
    echo "  Fetching $lib"
    curl -fSL "$CDN/libraries/$lib" -o "public/libraries/$lib" 2>/dev/null || \
      echo "  Warning: $lib not available on CDN (skipping)"
  fi
done

echo "Pre-build complete."
