name: Test Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20, 22 ]
        mode: [ 'dev', 'prod' ]
    name: Node${{ matrix.node }}
    env:
      CI: true
      START_MODE: ${{ matrix.mode }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: make public
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-node${{ matrix.node }}
          path: dist
          retention-days: 30
      - run: npm run test:e2e
